version: "3.11"
services:
  iki_diff_base:
    image: ghcr.io/rwu-r2m/r2m_diff_bot:latest
    container_name: iki_diff_base
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 69
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      QT_X11_NO_MITSHM: '1'
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../ros2_control_demos:/root/ros2_ws/src/ros2_control_demos
    command:
        - bash
        - -c
        - |
          source /opt/ros/jazzy/setup.bash
          source /root/ros2_ws/install/setup.bash
          tail -f /dev/null
          #ros2 launch ros2_control_demo_example_2 diffbot.launch.py
